---
title: "ETC3430 Assignment 1"
author: "Chelaka Paranahewa"
output: 
  pdf_document:
    fig_crop: false
---
    
```{r Setup, echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(readxl)
library(expm)
library(glue)
setwd("C:/Users/chela/GitHub Local Repo/Uni-Work/ETC3430/Assignments/")
set.seed(31455034)
```

# Question 1
## Part A
```{r Transition Matrix}
P <- matrix(
    data = c(0.45, 0.35, 0.20, 0.36, 0.34, 0.30, 0.25, 0.65, 0.10),
    nrow = 3, ncol = 3, byrow = TRUE
)
```

## Part B
```{r Most likely states within the next 5 days}
print(glue("Most likely states within the next 5 days"))
for (day in 0:5) {
    print(glue("Day: {day}"))
    print(P %^% day)
    cat("\n\n")
}
```

## Part C
```{r Expected state within the next 5 days}
print(glue("Expected state within the next 5 days"))
for (day in 0:5) {
    print(glue("Day: {day}"))
    print((P %^% day) %*% matrix(1:3))
    cat("\n\n")
}
```

## Part E
```{r Histograms of distribution , fig.width = 9, fig.height = 5, warning=FALSE, message=FALSE}
set.seed(3149)
P <- matrix(
    data = c(0.45, 0.35, 0.20, 0.36, 0.34, 0.30, 0.25, 0.65, 0.10),
    nrow = 3, ncol = 3, byrow = TRUE
)

# Cumulative Probability
CP <- t(apply(P, 1, cumsum))

repeater <- function(sim_size) {
    X <- matrix(0, sim_size + 1, 1)
    X[1, 1] <- 1
    for (day in 1:3) {
        for (i in 1:sim_size) {
            u <- runif(1)
            X[i + 1, 1] <- 1 * (u < CP[X[i, 1], 1]) +
                2 * (u < CP[X[i, 1], 2]) * (u > CP[X[i, 1], 1]) +
                3 * (u > CP[X[i, 1], 2])
        }

        g <- X %>%
            as_tibble() %>%
            ggplot(aes(x = V1)) +
            geom_histogram() +
            labs(
                title = paste("Day ", day),
                subtitle = paste("n =  ", sim_size),
                x = "State"
            )
        print(g)
    }
}
sims <- c(100, 1000, 10000, 100000)
for (index in 1:4) {
    repeater(sims[index])
}
```


## Part F
```{r Monte Carlo estimation Day1 is Sunny}
## Part F
set.seed(31455034)
P <- matrix(
    data = c(0.45, 0.35, 0.20, 0.36, 0.34, 0.30, 0.25, 0.65, 0.10), # these are my vals so pls change lol
    nrow = 3, ncol = 3, byrow = TRUE
)

# Cumulative Probability
CP <- t(apply(P, 1, cumsum))
markov_proc_del_start <- function(sim_size, starting_day) {
    X <- matrix(1, sim_size + 1, 1)
    for (day in starting_day:3) {
        for (i in 1:sim_size) {
            u <- runif(1)
            X[i, 1] <- 1 * (u < CP[X[i, 1], 1]) +
                2 * (u < CP[X[i, 1], 2]) * (u > CP[X[i, 1], 1]) +
                3 * (u > CP[X[i, 1], 2])
        }
    }
    pi <- matrix(0, 1, 3)
    pi[1, 1] <- sum(X == 1) / sim_size
    pi[1, 2] <- sum(X == 2) / sim_size
    pi[1, 3] <- sum(X == 3) / sim_size
    return(pi)
}

set.seed(31455034)
sims <- c(100, 1000, 10000, 100000)
for (index in 1:4) {
    result <- markov_proc_del_start(sims[index], 2)
    print(glue("Simulation size: {sims[index]}"))
    print(result)
    print(glue("Pr(X_3>1|X_1=1) = {result[1,2]} + {result[1,3]}"))
    print(glue("Pr(X_3>1|X_1=1) = {result[1,2] + result[1,3]}"))
    cat("\n\n")
}

result <- c(1, 0, 0) %*% (P %^% 2)
print(glue("Theoretical Value:"))
print(result)
print(glue("Pr(X_3>1|X_1=1) = {result[1,2]} + {result[1,3]}"))
print(glue("Pr(X_3>1|X_1=1) = {result[1,2] + result[1,3]}"))
```

## Part G
```{r Monte Carlo estimation Day2 is Sunny)}
## Part G
set.seed(31455034)
sims <- c(100, 1000, 10000, 100000)
for (index in 1:4) {
    result <- markov_proc_del_start(sims[index], 3)
    print(glue("Simulation size: {sims[index]}"))
    print(result)
    print(glue("Pr(X_3>1|X_2=1) = {result[1,2]} + {result[1,3]}"))
    print(glue("Pr(X_3>1|X_2=1) = {result[1,2] + result[1,3]}"))
    cat("\n\n")
}

result <- c(1, 0, 0) %*% (P %^% 1)
print(glue("Theoretical Value:"))
print(result)
print(glue("Pr(X_3>1|X_2=1) = {result[1,2]} + {result[1,3]}"))
print(glue("Pr(X_3>1|X_2=1) = {result[1,2] + result[1,3]}"))
```


# Question 2
## Part A
```{r TM Dataset1}
data_sheet1 <- read_excel("Data.xlsx", sheet = 1) %>%
    select(Dataset1, Dataset2)

data_sheet1 <- data_sheet1[-c(1), ]

data_sheet1 <- transform(
    data_sheet1,
    Dataset1 = as.numeric(Dataset1),
    Dataset2 = as.numeric(Dataset2)
)

count_matrix1 <- matrix(0, 3, 3)

# Creating Count
for (index in 2:length(data_sheet1$Dataset1)) {
    row <- data_sheet1$Dataset1[index - 1]
    col <- data_sheet1$Dataset1[index]
    count_matrix1[row, col] <- count_matrix1[row, col] + 1
}

# Starting state is 1 and first datapoint is 1
count_matrix1[1, 1] <- count_matrix1[1, 1] + 1
# view(count_matrix1)

# Creating transition
tran_mat1 <- matrix(c(
    count_matrix1[1, ] / sum(count_matrix1[1, ]),
    count_matrix1[2, ] / sum(count_matrix1[2, ]),
    count_matrix1[3, ] / sum(count_matrix1[3, ])
), 3, 3, byrow = TRUE)

# view(tran_mat1)


print(glue("Transition Matrix for Dataset 1"))
print(tran_mat1)
```

# Part B
```{r TM Dataset2}
count_matrix2 <- matrix(0, 3, 3)

# Creating Count
for (index in 2:length(data_sheet1$Dataset2)) {
    row <- data_sheet1$Dataset2[index - 1]
    col <- data_sheet1$Dataset2[index]
    count_matrix2[row, col] <- count_matrix2[row, col] + 1
}
# view(count_matrix2)

# Creating transition
tran_mat2 <- matrix(c(
    count_matrix2[1, ] / sum(count_matrix2[1, ]),
    count_matrix2[2, ] / sum(count_matrix2[2, ]),
    count_matrix2[3, ] / sum(count_matrix2[3, ])
), 3, 3, byrow = TRUE)

# view(tran_mat2)

print(glue("Transition Matrix for Dataset 2"))
print(tran_mat2)
```

# Part C
```{r Distribution Matrix in 10 periods}
periods <- 10
print(glue("Distribution Matrix of Dataset 1 in {periods} periods"))
print(c(1, 0, 0) %*% (tran_mat1 %^% periods))
cat("\n\n")

print(glue("Distribution Matrix of Dataset 2 in {periods} periods"))
print(c(1, 0, 0) %*% (tran_mat2 %^% periods))
cat("\n\n")
```

# Part D
Both Dataset 1 and Dataset 2's distribution matrices stablises to 4 decimal places by the time the period approaches 10. 


# Question 3
## Part A
```{r}
data_sheet2 <- read_excel("Data.xlsx", sheet = 2) %>%
    select(Dataset1, Dataset2)

data_sheet2 <- data_sheet2[-c(1), ]
states <- tibble(state = rep(1:2, times = length(data_sheet2$Dataset1) / 2 + 1))
states <- states[-c(length(data_sheet2$Dataset1) + 1), ]
data_sheet2 <- data_sheet2 %>% cbind(states)
data_sheet2 <- transform(
    data_sheet2,
    Dataset1 = as.numeric(Dataset1),
    Dataset2 = as.numeric(Dataset2)
)
data_sheet2 <- data_sheet2 %>% as_tibble()


lambda_states1 <- data_sheet2 %>%
    select(Dataset1, state) %>%
    group_by(state) %>%
    summarise(lambda = 1 / mean(Dataset1))

# Make intensity matrix
int_matrix1 <- matrix(
    c(
        -lambda_states1$lambda[1], lambda_states1$lambda[1],
        lambda_states1$lambda[2], -lambda_states1$lambda[2]
    ),
    2, 2, TRUE
)
int_matrix1



lambda_states2 <- data_sheet2 %>%
    select(Dataset2, state) %>%
    group_by(state) %>%
    summarise(lambda = 1 / mean(Dataset2))

# Make intensity matrix
int_matrix2 <- matrix(
    c(
        -lambda_states2$lambda[1], lambda_states2$lambda[1],
        lambda_states2$lambda[2], -lambda_states2$lambda[2]
    ),
    2, 2, TRUE
)
int_matrix2
```

<!-- # int_mat_contructor <- function(data, dataset) {
#     lambda_states <- data %>%
#         select(dataset, state) %>%
#         group_by(state) %>%
#         summarise(lambda = 1 / mean(data[dataset]))
#     print(data)
#     print(data[dataset])
#     print(lambda_states)
#     # Make intensity matrix
#     int_mat <- matrix(
#         c(
#             -lambda_states$lambda[1], lambda_states$lambda[1],
#             lambda_states$lambda[2], -lambda_states$lambda[1]
#         ),
#         2, 2, TRUE
#     )
#     return(int_mat)
# }

# print(int_mat_contructor(data_sheet2, "Dataset1")) -->

```{r}

```