---
head-includes:
    - \usepackage{mathtools}
output: pdf_document
---

# Question 2
### Part A
\begin{align*}
    \hat{u}_i &= residuals \\
    {\hat{u}}_i &= y_i-{\hat{y}}_i,\ i = 1, 2, ... n && \text {from Assignment Property (7)}\\
    &= y_i-\left({\hat{\beta}}_o+{\hat{\beta}}_1x_i\right) && \text {by definition } \hat y_i = \hat \beta_0 + \hat \beta_1 x_i\\
    &= y_i-{\hat{\beta}}_o-{\hat{\beta}}_1x_i
\end{align*}

\begin{align*}
    \sum _{i=1}^n \hat{u}_i &= \sum_{i=1}^{n}{y_i - (\hat \beta_0 + \hat \beta_1 x_i)} \\
    &= \sum_{i=1}^{n}{y_i} - \sum_{i=1}^{n}{(\hat \beta_0 + \hat \beta_1 x_{i})} \\
    &= \sum_{i=1}^{n}{y_i} - \sum_{i=1}^{n}{\hat \beta_0} - \sum_{i=1}^n{\hat \beta_1 x_{i}} \\
    &= \sum_{i=1}^{n}{y_i} - \sum_{i=1}^n{\hat \beta_1 x_{i}} - n{\hat \beta_0} && \text {rearranging terms and summing $\hat \beta_0$} \\
    &= \frac{n}{n} \sum_{i=1}^{n}{y_i} - \frac{n}{n} \sum_{i=1}^n{\hat \beta_1 x_{i}} - n{\hat \beta_0} && \text {times first and second sum by $\frac{n}{n}$} \\
    &= n \bar y - n \hat \beta_i \bar{x} - n \hat \beta_0 \\
    &= n \bar y - n \hat \beta_i \bar{x} - n (\bar y - \hat \beta_i \bar{x}) && \text {substituting from Assignment Property (6)} \\
    &= n \bar y - n \hat \beta_i \bar{x} - n \bar y + n\hat \beta_i \bar{x} \\
    &= n \bar y - n \bar y - n \hat \beta_i \bar{x} + n\hat \beta_i \bar{x} \\
    &= 0
\end{align*}


### Part B

\begin{align*}
    SSR\ \left(b_0,b_1\right) &=\sum_{i=1}^{n}\left(y_i-b_0-b_1x_i\right)^2 \\
    \left.\frac{\partial SSR\left(b_0,b_1\right)}{\partial b_0}\right|_{{\hat{\beta}}_0,{\hat{\beta}}_1} &= -2\sum_{i=1}^{n}{\left(y_i- \hat \beta_0-\hat \beta_1x_i\right)=0} \\
    \left.\frac{\partial SSR\left(b_0,b_1\right)}{\partial b_i}\right|_{{\hat{\beta}}_0,{\hat{\beta}}_1} &= -2\sum_{i=1}^{n}{x_i\left(y_i-\hat \beta_0-\hat \beta_1x_i\right)=0} && \text {call this (1)} \\
    \\
    {\hat{u}}_i &= y_i-{\hat{y}}_i,\ i = 1, 2, ... n && \text {from Assignment Property (7)}\\
    &= y_i-\left({\hat{\beta}}_o+{\hat{\beta}}_1x_i\right) && \text {by definition } \hat y_i = \hat \beta_0 + \hat \beta_1 x_i\\
    &= y_i-{\hat{\beta}}_o-{\hat{\beta}}_1x_i && \text {call this (2)}\\
\end{align*}

\begin{align*}
    -2\sum_{i=1}^{n}x_i (\hat u_i) &= 0 && \text {substituting (2) into (1)} \\
    \sum_{i=1}^{n}x_i \hat u_i &= 0 && \text {call this (3)}
\end{align*}

Now if 
$\boldsymbol{x} = \underset{(n \times 1)}{
\begin{pmatrix}
    x_{1} \\
    \vdots \\
    x_{n}
\end{pmatrix}}$ and 
$\boldsymbol{\hat u} =\underset{(n \times 1)}{ 
\begin{pmatrix}
    \hat u_{1} \\
    \vdots \\
    \hat u_{n}
\end{pmatrix}}$ then
the dot product is 

\begin{align*}
    {\boldsymbol{x' \hat u}} &= \begin{pmatrix} x_{1} && ... && x_{n} \end{pmatrix}
    \begin{pmatrix} \hat u_{1} \\ \vdots \\ \hat u_{n} \end{pmatrix} \\
    &= x_1 \hat u_1 +\ ...\ + x_n \hat u_n && \text {just the linear combinations of column vector ${\boldsymbol u}$}\\
    & && \text {where the scalars are the components of ${\boldsymbol{x}}$} \\
    &= \sum_{i=1}^{n}x_i \hat u_i \\
    &= 0 && \text {from (3)}
\end{align*}