---
title: "ETC3550 Assignment 6"
author: "Chelaka Paranahewa"
output: 
  pdf_document:
    fig_crop: false
---

```{r Setup, echo = FALSE, include = FALSE}
library(fpp3, warn.conflicts = FALSE)
library(broom, warn.conflicts = FALSE)
library(glue, warn.conflicts = FALSE)
# sessionInfo()
# Use your student ID as the seed
set.seed(31455034)
myseries <- aus_retail %>%
    # Remove discontinued series
    filter(!(`Series ID` %in% c(
        "A3349561R", "A3349883F", "A3349499L", "A3349902A",
        "A3349588R", "A3349763L", "A3349372C", "A3349450X",
        "A3349679W", "A3349378T", "A3349767W", "A3349451A"
    ))) %>%
    # Select a series at random
    filter(`Series ID` == sample(`Series ID`, 1))
```
1. Find the best ETS model for your retail data. (i.e., find the model with the minimum AICc value computed using all available data).

```{r}
fit <- myseries %>%
    model(ETS(Turnover))
fit
fit %>%
    glance()
```
```{r, echo = FALSE}
# fit <- myseries %>% model(
#     # Additive
#     ANN =  ETS(Turnover ~ error("A") + trend("N") + season("N")),
#     ANA =  ETS(Turnover ~ error("A") + trend("N") + season("A")),
#     ANM =  ETS(Turnover ~ error("A") + trend("N") + season("M")),
#     AAN =  ETS(Turnover ~ error("A") + trend("A") + season("N")),
#     AAA =  ETS(Turnover ~ error("A") + trend("A") + season("A")),
#     AAM =  ETS(Turnover ~ error("A") + trend("A") + season("M")),
#     AAdN = ETS(Turnover ~ error("A") + trend("Ad") + season("N")),
#     AAdA = ETS(Turnover ~ error("A") + trend("Ad") + season("A")),
#     AAdM = ETS(Turnover ~ error("A") + trend("Ad") + season("M")),

#     # Multiplicative
#     MNN =  ETS(Turnover ~ error("M") + trend("N") + season("N")),
#     MNA =  ETS(Turnover ~ error("M") + trend("N") + season("A")),
#     MNM =  ETS(Turnover ~ error("M") + trend("N") + season("M")),
#     MAN =  ETS(Turnover ~ error("M") + trend("A") + season("N")),
#     MAA =  ETS(Turnover ~ error("M") + trend("A") + season("A")),
#     MAM =  ETS(Turnover ~ error("M") + trend("A") + season("M")), #*
#     MAdN = ETS(Turnover ~ error("M") + trend("Ad") + season("N")),
#     MAdA = ETS(Turnover ~ error("M") + trend("Ad") + season("A")),
#     MAdM = ETS(Turnover ~ error("M") + trend("Ad") + season("M"))
# )

# ets <- fit %>%
#     select(mable_vars(fit)) %>%
#     glance()

# index <- ets$AICc %>% which.min()

# glue(
#     "The model with the lowest AICc is a {ets[[index, '.model']]} model, \\
#     with an AICc of {ets[[index, 'AICc']]}"
# )
```

2. Now use time series cross-validation on your data to compare the model from step 1, along with ETS(M,N,M), ETS(M,A,M) and ETS(M,Ad,M) models.

```{r}
training <- myseries %>%
    stretch_tsibble(.init = 48, .step = 48)

training %>%
    model(
        Best = ETS(Turnover),
        MNM =  ETS(Turnover ~ error("M") + trend("N") + season("M")),
        MAM =  ETS(Turnover ~ error("M") + trend("A") + season("M")), #*
        MAdM = ETS(Turnover ~ error("M") + trend("Ad") + season("M"))
    ) %>%
    forecast(h = 1) %>%
        accuracy(myseries)
```


3. Which model do you prefer for your data? Explain your answer.
<!-- TEXT -->