```{r Setup, echo = FALSE, include = FALSE}
library(fpp3, warn.conflicts = FALSE)

# Use your student ID as the seed
set.seed(31455034)
myseries <- aus_retail %>%
    # Remove discontinued series
    filter(!(`Series ID` %in% c(
        "A3349561R", "A3349883F", "A3349499L", "A3349902A",
        "A3349588R", "A3349763L", "A3349372C", "A3349450X",
        "A3349679W", "A3349378T", "A3349767W", "A3349451A"
    ))) %>%
    # Select a series at random
    filter(`Series ID` == sample(`Series ID`, 1))
```

# Question 1
```{r autoplot}
myseries %>%
    autoplot(Turnover) +
    labs(title = "Australia Retail Turnover", subtitle = "South Australia") +
    ylab("Turnover [million $AUD]")
```
<!-- Analysis -->
From the graph, it can be gathered that there is a trend pointing up with variance that begins small and gradually grows to a considerable size. The graph also contains seasonalities around Q4.


# Question 2
```{r gg_season}
myseries %>%
    gg_season(Turnover, labels = "both") +
    labs(title = "Australia Retail Turnover", subtitle = "South Australia") +
        ylab("Turnover [million $AUD]")
```
<!-- Analysis -->


# Question 3
```{r gg_subseries()}
myseries %>%
    gg_subseries(Turnover) +
    labs(title = "Australia Retail Turnover", subtitle = "South Australia") +
        ylab("Turnover [million $AUD]")
```
<!-- Analysis -->


