```{r}
library(fpp3)
library(tidyverse)
setwd("C:/Users/chela/OneDrive - Monash University/ETC3550/Tutorials/T3")
```

# Question 7
```{r}
aus_arrivals %>% autoplot()
aus_arrivals %>% gg_subseries()
aus_arrivals %>% gg_season()
```

# Question 8
```{r}
# Use your student ID as the seed
set.seed(31455034)
myseries <- aus_retail %>%
    # Remove discontinued series
    filter(!(`Series ID` %in% c(
        "A3349561R", "A3349883F", "A3349499L", "A3349902A",
        "A3349588R", "A3349763L", "A3349372C", "A3349450X",
        "A3349679W", "A3349378T", "A3349767W", "A3349451A"
    ))) %>%
    # Select a series at random
    filter(`Series ID` == sample(`Series ID`, 1))
myseries %>%
    autoplot(Turnover) +
    labs(title = "Australia Retail Turnover", subtitle = "South Australia") +
    ylab("Turnover [million $AUD]")


myseries %>%
    gg_season(Turnover, labels = "both") +
    labs(title = "Australia Retail Turnover", subtitle = "South Australia") +
    ylab("Turnover [million $AUD]")

myseries %>%
    gg_subseries(Turnover) +
    labs(title = "Australia Retail Turnover", subtitle = "South Australia") +
    ylab("Turnover [million $AUD]")
```

# Question 9
```{r}

us_employment %>% filter(Title == "Total Private") -> x

x %>% autoplot(Employed)
x %>% gg_season(Employed)
x %>% gg_subseries(Employed)
x %>% gg_lag(Employed, lags = 1:14)
x %>%
    ACF(Employed, max_lag = 12) %>%
    autoplot()
```

# Question 11
```{r}
aus_livestock %>%
    filter(
        State == "Victoria",
        Animal == "Pigs",
        year(Month) >= 1990,
        year(Month) <= 1995
    ) %>%
    ACF(Count, max_lag = 48) %>%
    autoplot() +
    labs(title = "Pigs slaughtered", subtitle = "In Victoria")

aus_livestock %>%
    filter(
        State == "Victoria",
        Animal == "Pigs",
        year(Month) >= 1990,
        year(Month) <= 1995
    ) %>%
    autoplot() +
    labs(title = "Pigs slaughtered", subtitle = "In Victoria")
```

```{r}
dgoog <- gafa_stock %>%
    filter(Symbol == "GOOG", year(Date) >= 2018) %>%
    mutate(trading_day = row_number()) %>%
    update_tsibble(index = trading_day, regular = TRUE) %>%
    mutate(diff = difference(Close))
```