---
title: "ETC3550 Assignment 5"
author: "Chelaka Paranahewa"
output: 
  html_document:
    fig_crop: false
---

```{r Setup, echo = FALSE, include = FALSE}
library(fpp3, warn.conflicts = FALSE)
library(tidyverse, warn.conflicts = FALSE)
```

```{r Simple Exponential Smoothing Function}
ses_func <- function(y, forecast = 1, alpha_input = 0) {
    smooth_function <- function(y, alpha, level, sse_mode = FALSE) {
        n <- length(y)
        levels <- numeric(n + 1)
        # levels[1] <- level
        # for (t in 1:n) {
        #     levels[t + 1] <- alpha * y[t] + (1 - alpha) * levels[t]
        # }
        levels[1] <- alpha * y[1] + (1 - alpha) * level

        for (t in 1:n) {
            levels[t + 1] <- alpha * y[t] + (1 - alpha) * levels[t]
        }
        # Returns Sum of Squared Errors
        if (sse_mode) {
            return(sum((y - levels[- (n + 1)])^2))
        }

        # Returns yhat_(t+h)
        return(levels[n + 1])
        # return(tail(levels, 5))
    }

    sse <- function(par, y) return(smooth_function(y, par[1], par[2], TRUE))

    best_val <- optim(
        par = c(
            alpha = alpha_input,
            level = y[1]
        ),
        fn = sse,
        y = y
    )

    # Forecast you return the same value for any value of h
    # Since the formula for SES shows that h has no influence 
    # on the final output
    return(smooth_function(y, best_val$par[1], best_val$par[2]))
}

piggies <- aus_livestock %>%
    filter(Animal == "Pigs", State == "Victoria")
glue::glue("Custom Funct outputs {ses_func(piggies$Count)}")
print("ETS model outputs")
fc <- piggies %>%
    model(ETS(Count ~ error("A") + trend("N") + season("N"))) %>%
    forecast(h = 1)
fc[6]
```

```{r Function Tests}
piggies <- aus_livestock %>%
    filter(Animal == "Pigs", State == "Victoria")

glue::glue("Custom Funct outputs {ses_func(piggies$Count)}")
# ses_func(piggies$Count, 1, 0)

print("ETS model outputs")
fc <- piggies %>%
    model(ETS(Count ~ error("A") + trend("N") + season("N"))) %>%
    forecast(h = 1)

fc[6]
```